package com.paandaaa.homey.android.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity(tableName = "recipes")
data class RecipeEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val remoteId: String?, // If coming from an API, store its ID
    val title: String,
    val imageUrl: String?,
    val ingredients: List<String>,
    val instructions: String,
    val isFavorite: Boolean = false,
    val generatedByAi: Boolean = false // Track if generated by AI
)